image: quay.io/ansible/creator-ee:latest

stages:
  - validate

validate-playbooks:
  stage: validate
  before_script:
    - ansible-galaxy collection install -r requirements.yml -p ./collections
  script:
    - ansible-playbook --syntax-check playbooks/f5os_connectivity.yml
    - ansible-playbook --syntax-check playbooks/bigip_connectivity.yml
    - ansible-playbook --syntax-check playbooks/bigip_virtual_server_example.yml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH
